#!/bin/sh
mount -t proc     proc /proc
mount -t sysfs    sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || mount -t tmpfs -o mode=0755 none /dev
[ -c /dev/console ] || mknod -m 600 /dev/console c 5 1
[ -c /dev/null ]    || mknod -m 666 /dev/null    c 1 3
echo "=== initramfs ready ==="
exec setsid /bin/sh </dev/console >/dev/console 2>&1
