# Auto-generated NXP environment for Makefile inclusion
# Generated by: nxp_prepare_headers_imx.sh --arch arm
export ARCH := arm
export CROSS_COMPILE := arm-linux-gnueabihf-
export SYSROOT := /home/jorge/challenge-2509/simtemp-system/simtemp/scripts/sysroot-arm
export KDIR := /home/jorge/challenge-2509/simtemp-system/deployment/qemu/linux-imx-5.10
export KERNEL_SRC := /home/jorge/challenge-2509/simtemp-system/deployment/qemu/linux-imx-5.10
