#!/usr/bin/env bash
# prepare_headers_imx.sh
# Prepare NXP linux-imx headers/sysroot for cross builds and optional module prep.
# Usage:
#   ./prepare_headers_imx.sh [--arch arm|arm64] [--sysroot DIR] [--kernel-src DIR | --kernel-tag TAG] [--toolchain-prefix PREFIX] [--modules] [--jobs N]
# Defaults:
#   --arch arm
#   --kernel-tag lf-5.10.72-2.2.0
#   --sysroot $PWD/sysroot-${ARCH}
#   --toolchain-prefix (arm -> arm-linux-gnueabihf-, arm64 -> aarch64-linux-gnu-)
set -euo pipefail

ARCH="arm"
KERNEL_TAG="lf-5.10.72-2.2.0"
KERNEL_SRC=""
SYSROOT=""
TOOLCHAIN_PREFIX=""
DO_MODULES="0"
JOBS="$(nproc || echo 4)"

log(){ printf "[imx] %s\n" "$*" >&2; }

usage(){
  sed -n '1,35p' "$0" | sed 's/^# \{0,1\}//'
  exit 1
}

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch) ARCH="$2"; shift 2;;
    --kernel-tag) KERNEL_TAG="$2"; shift 2;;
    --kernel-src) KERNEL_SRC="$(realpath -m "$2")"; shift 2;;
    --sysroot) SYSROOT="$(realpath -m "$2")"; shift 2;;
    --toolchain-prefix) TOOLCHAIN_PREFIX="$2"; shift 2;;
    --modules) DO_MODULES="1"; shift 1;;
    --jobs) JOBS="$2"; shift 2;;
    -h|--help) usage;;
    *) log "Unknown arg: $1"; usage;;
  esac
done

case "$ARCH" in
  arm|arm32) ARCH="arm"; DEF_PREFIX="arm-linux-gnueabihf-";;
  arm64|aarch64) ARCH="arm64"; DEF_PREFIX="aarch64-linux-gnu-";;
  *) log "Unsupported --arch: $ARCH"; exit 2;;
esac

[[ -z "${TOOLCHAIN_PREFIX}" ]] && TOOLCHAIN_PREFIX="$DEF_PREFIX"
[[ -z "${SYSROOT}" ]] && SYSROOT="$(pwd)/sysroot-${ARCH}"

# Checks
need() { command -v "$1" >/dev/null 2>&1 || { log "Missing tool: $1"; exit 3; }; }
need git
need make

log "ARCH=$ARCH"
log "KERNEL_TAG=$KERNEL_TAG"
log "SYSROOT=$SYSROOT"
log "TOOLCHAIN_PREFIX=$TOOLCHAIN_PREFIX"
log "DO_MODULES=$DO_MODULES"
log "JOBS=$JOBS"

# Acquire kernel source
if [[ -z "$KERNEL_SRC" ]]; then
  # Check for existing workspace linux-imx (compiled version)
  EXISTING_IMX="../../deployment/qemu/linux-imx-5.10"
  if [[ -d "$EXISTING_IMX" && -f "$EXISTING_IMX/.config" ]]; then
    log "Found existing compiled linux-imx in workspace: $EXISTING_IMX"
    KERNEL_SRC="$(realpath "$EXISTING_IMX")"
  else
    # Clone fresh copy
    KERNEL_SRC="$(pwd)/linux-imx"
    if [[ ! -d "$KERNEL_SRC/.git" ]]; then
      log "Cloning NXP linux-imx…"
      git clone --depth=1 --branch "$KERNEL_TAG" https://github.com/nxp-imx/linux-imx.git "$KERNEL_SRC"
    else
      log "Reusing existing repo at $KERNEL_SRC"
      (cd "$KERNEL_SRC" && git fetch --depth=1 origin "$KERNEL_TAG" && git checkout -f "$KERNEL_TAG")
    fi
  fi
else
  log "Using provided kernel source: $KERNEL_SRC"
fi

# Create sysroot
mkdir -p "$SYSROOT/usr"

# Install userspace headers from kernel (for libc/kernel uapi)
log "Installing headers into $SYSROOT/usr …"
make -C "$KERNEL_SRC" \
  ARCH="$ARCH" \
  CROSS_COMPILE="$TOOLCHAIN_PREFIX" \
  headers_install \
  INSTALL_HDR_PATH="$SYSROOT/usr"

# Optional: prepare for external module builds (creates scripts, generated headers)
if [[ "$DO_MODULES" == "1" ]]; then
  log "Running 'make modules_prepare' to enable out-of-tree module builds…"
  # A defconfig is required for proper generated headers; pick a reasonable default
  case "$ARCH" in
    arm) DEFCONF="multi_v7_defconfig";;
    arm64) DEFCONF="defconfig";;
  esac
  if [[ ! -f "$KERNEL_SRC/.config" ]]; then
    log "Applying defconfig: $DEFCONF"
    make -C "$KERNEL_SRC" ARCH="$ARCH" CROSS_COMPILE="$TOOLCHAIN_PREFIX" "$DEFCONF"
  fi
  make -C "$KERNEL_SRC" ARCH="$ARCH" CROSS_COMPILE="$TOOLCHAIN_PREFIX" -j"$JOBS" olddefconfig
  make -C "$KERNEL_SRC" ARCH="$ARCH" CROSS_COMPILE="$TOOLCHAIN_PREFIX" -j"$JOBS" modules_prepare
fi

# Write environment files
ENV_FILE="$(pwd)/imx-env.sh"
cat > "$ENV_FILE" <<EOF
# Source this file:  source ./imx-env.sh
export ARCH="${ARCH}"
export CROSS_COMPILE="${TOOLCHAIN_PREFIX}"
export SYSROOT="${SYSROOT}"
export KERNEL_SRC="${KERNEL_SRC}"
# For pkg-config cross lookups (adjust if needed)
export PKG_CONFIG_SYSROOT_DIR="\$SYSROOT"
export PKG_CONFIG_LIBDIR="\$SYSROOT/usr/lib/pkgconfig:\$SYSROOT/usr/lib/${DEF_PREFIX%\-}/pkgconfig:\$SYSROOT/usr/share/pkgconfig"
export PKG_CONFIG_PATH=
# For kernel module builds (if --modules was used)
export KDIR="\$KERNEL_SRC"
EOF

# Write Makefile-compatible environment
MAKEFILE_ENV="$(pwd)/imx-env.mk"
cat > "$MAKEFILE_ENV" <<EOF
# Auto-generated NXP environment for Makefile inclusion
# Generated by: nxp_prepare_headers_imx.sh --arch ${ARCH}
export ARCH := ${ARCH}
export CROSS_COMPILE := ${TOOLCHAIN_PREFIX}
export SYSROOT := ${SYSROOT}
export KDIR := ${KERNEL_SRC}
export KERNEL_SRC := ${KERNEL_SRC}
EOF

log "Wrote environment exports to: $ENV_FILE"
log "Wrote Makefile environment to: $MAKEFILE_ENV"
log "Done."
log "NXP ${ARCH} cross-compilation environment ready!"
echo ""
echo "Integration with simtemp project:"
echo "  cd ../kernel"
if [[ "$ARCH" == "arm" ]]; then
  echo "  make nxp-arm          # Build nxp_simtemp.ko for ARM"
else
  echo "  make nxp-arm64        # Build nxp_simtemp.ko for ARM64"
fi
echo "  make info             # Show build configuration"
echo ""
echo "Manual usage:"
echo "  source ./imx-env.sh"
echo "  # Example userland build:"
echo "  \${CROSS_COMPILE}gcc -o hello.\$ARCH hello.c --sysroot=\$SYSROOT"
if [[ "$DO_MODULES" == "1" ]]; then
  echo "  # Example external module build:"
  echo "  make -C \$KDIR ARCH=\$ARCH CROSS_COMPILE=\$CROSS_COMPILE M=\$PWD modules"
fi
